name: Site Lint / Heading ID check

on:
  push:
    branches:
      - main # change this if your default branch is named differently
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint on node 12.x and ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.7.10
<<<<<<< HEAD:.github/workflows/beta_site_lint.yml
        with:
          working-directory: 'beta'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-reactjs-tr-org-beta

=======
>>>>>>> 543c7a0dcaf11e0400a9deb2465190467e272171:.github/workflows/site_lint.yml

      - name: Lint codebase
        run: yarn ci-check
